Repository AdvancedCSS2024/idg1293-2024-oblig3-group09, pull requests merged in 2024-05, with the labels that each got.

#50 Sync main
  assets/graphics/images/cleanup_boat_2.svg
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: animation upload/creation

#53 Replaced cleanup boat SVGs, worked on animation
  assets/graphics/images/cleanup_boat.svg
  assets/graphics/images/cleanup_boat_2.svg
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: asset upload/creation, animation upload/creation

#54 Added source list, replaced boat w/people moving SVG
  assets/graphics/images/boat_with_people_moving.svg
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: documentation

#57 Last fixes & additions to the project delivery
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: enhancement, animation upload/creation

#58 Fixed writing in scene 1 a bit
  index.html
Labels: enhancement

#59 Fixed scroll animation on Scene 7
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: enhancement

#60 Sync main
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: enhancement

#61 Better clouds
  assets/styles/style.css
  assets/styles/style.css.map
  assets/styles/style.scss
  index.html
Labels: enhancement
